"""milestone 2

Revision ID: 135f1e5ec5c3
Revises: 2027f6a4c112
Create Date: 2026-03-24 22:40:14.432568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135f1e5ec5c3'
down_revision: Union[str, None] = '2027f6a4c112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
